--------------------------------------------------------
-- Archivo creado  - miércoles-enero-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ABONO_AGENTE
--------------------------------------------------------

  CREATE TABLE "ABONO_AGENTE" ("AGENTE_COD_AGENTE" NUMBER(4,0), "VALOR_ABONO" NUMBER(13,2), "FECHA_ABONO" DATE, "OBSERVACION" VARCHAR2(1000 BYTE), "CONSECUTIVO" NUMBER(5,0)) 

   COMMENT ON COLUMN "ABONO_AGENTE"."AGENTE_COD_AGENTE" IS 'CODIGO DEL AGENTE'
   COMMENT ON COLUMN "ABONO_AGENTE"."VALOR_ABONO" IS 'VALOR DEL ABONO'
   COMMENT ON COLUMN "ABONO_AGENTE"."FECHA_ABONO" IS 'FECHA DEL ABONO'
   COMMENT ON COLUMN "ABONO_AGENTE"."OBSERVACION" IS 'OBSERVACION'
   COMMENT ON COLUMN "ABONO_AGENTE"."CONSECUTIVO" IS 'NUMERO CONSECUTIVO DEL ABONO'
--------------------------------------------------------
--  DDL for Table AGENTE
--------------------------------------------------------

  CREATE TABLE "AGENTE" ("COD_AGENTE" NUMBER(4,0), "NOMBRE_AGENTE" VARCHAR2(100 BYTE)) 

   COMMENT ON COLUMN "AGENTE"."COD_AGENTE" IS 'CODIGO DEL AGENTE DE GESTION'
   COMMENT ON COLUMN "AGENTE"."NOMBRE_AGENTE" IS 'NOMBRE DEL AGENTE DE GESTION'
   COMMENT ON TABLE "AGENTE"  IS 'AGENTE QUE SE GESTIONA EL CLIENTE'
--------------------------------------------------------
--  DDL for Table CALC_GESTION
--------------------------------------------------------

  CREATE TABLE "CALC_GESTION" ("AGENTE_COD_AGENTE" NUMBER(4,0), "FACTCONT_CONTRATO_ID_CONTRATO" NUMBER(20,0), "FACTCONT_FAFACTURA_IDFACTURA" NUMBER, "VALOR_AJUSTE_IMPUESTO" NUMBER(13,2), "VALOR_AJUSTE_CLOUD" NUMBER(13,2), "VALOR_BASE_GESTION" NUMBER(13,2), "VALOR_COSTO_LEGALIZACION" NUMBER(13,2), "VALOR_ASUMIDO_LEGALIZACION" NUMBER(13,2), "VALOR_GESTION" NUMBER(13,2), "FECHA_LIQUIDACION" DATE, "VALOR_GESTION_PAGO" NUMBER(13,2), "OBSERVACION" VARCHAR2(1000 BYTE), "VALOR_GESTION_CONT_ANTERIOR" NUMBER(13,2)) 

   COMMENT ON COLUMN "CALC_GESTION"."VALOR_AJUSTE_IMPUESTO" IS 'VALOR DEL AJUSTE POR IMPUESTOS'
   COMMENT ON COLUMN "CALC_GESTION"."VALOR_AJUSTE_CLOUD" IS 'VALOR AJUSTE DEL SERVICIO CLOUD'
   COMMENT ON COLUMN "CALC_GESTION"."VALOR_BASE_GESTION" IS 'VALOR BASE PARA EL CALCULO DE LA GESTION'
   COMMENT ON COLUMN "CALC_GESTION"."VALOR_COSTO_LEGALIZACION" IS 'VALOR DEL COSTO DE LEGALIZACION DE LA GESTION'
   COMMENT ON COLUMN "CALC_GESTION"."VALOR_ASUMIDO_LEGALIZACION" IS 'VALOR ASUMIDO DE LA LEGALIZACION'
   COMMENT ON COLUMN "CALC_GESTION"."VALOR_GESTION" IS 'VALOR DE LA GESTION SIN LEGALIZACION'
   COMMENT ON COLUMN "CALC_GESTION"."FECHA_LIQUIDACION" IS 'FECHA LIQUIDACION DE LA COMISION'
   COMMENT ON COLUMN "CALC_GESTION"."VALOR_GESTION_PAGO" IS 'VALOR DE LA GESTION CON LEGALIZACION'
   COMMENT ON COLUMN "CALC_GESTION"."OBSERVACION" IS 'OBSERVACION'
   COMMENT ON COLUMN "CALC_GESTION"."VALOR_GESTION_CONT_ANTERIOR" IS 'VALOR COMISIONES CONTRATOS ANTERIORES'
   COMMENT ON TABLE "CALC_GESTION"  IS 'CALCULOS DE LA GESTION POR FACTURA'
--------------------------------------------------------
--  DDL for Table COND_GESTION
--------------------------------------------------------

  CREATE TABLE "COND_GESTION" ("AGENTE_COD_AGENTE" NUMBER(4,0), "CONTRATO_ID_CONTRATO" NUMBER(20,0), "POR_AJU_IMPUESTO_AÑO1" NUMBER(5,2), "VLR_CLOUD_AÑO1" NUMBER(13,2), "POR_ASUME_LEGALIZACION" NUMBER(5,2), "POR_BASE_GESTION" NUMBER(5,2), "POR_COSTO_LEGA_AÑO1" NUMBER(5,2), "POR_COSTO_LEGA_AÑO2" NUMBER(5,2), "POR_COSTO_LEGA_AÑO3" NUMBER(5,2), "POR_COSTO_LEGA_AÑO4" NUMBER(5,2), "VLR_CLOUD_AÑO2" NUMBER(13,2), "VLR_CLOUD_AÑO3" NUMBER(13,2), "VLR_CLOUD_AÑO4" NUMBER(13,2), "POR_AJU_IMPUESTO_AÑO2" NUMBER(5,2), "POR_AJU_IMPUESTO_AÑO3" NUMBER(5,2), "POR_AJU_IMPUESTO_AÑO4" NUMBER(5,2), "SALDO_CONTRATOS_ANTERIORES" NUMBER(13,2), "VLR_CUO_SALDO_ANTERIOR" NUMBER(13,2)) 

   COMMENT ON COLUMN "COND_GESTION"."POR_AJU_IMPUESTO_AÑO1" IS 'PORCENTAJE DE AJUSTE DE IMPUESTOS AÑO 1'
   COMMENT ON COLUMN "COND_GESTION"."VLR_CLOUD_AÑO1" IS 'VALOR CLOUD AÑO 1'
   COMMENT ON COLUMN "COND_GESTION"."POR_ASUME_LEGALIZACION" IS 'PORCENTAJE QUE SE ASUME DE LA LEGALIZACION'
   COMMENT ON COLUMN "COND_GESTION"."POR_BASE_GESTION" IS 'PORCENTAJE PARA PAGO DE GESTION'
   COMMENT ON COLUMN "COND_GESTION"."POR_COSTO_LEGA_AÑO1" IS 'PORCENTAJE DEL COSTO DE LEGALIZACION AÑO 1'
   COMMENT ON COLUMN "COND_GESTION"."POR_COSTO_LEGA_AÑO2" IS 'PORCENTAJE COSTO LEGALIZACION AÑO 2'
   COMMENT ON COLUMN "COND_GESTION"."POR_COSTO_LEGA_AÑO3" IS 'PORCENTAJE COSTO DE LEGALIZACION AÑO 3'
   COMMENT ON COLUMN "COND_GESTION"."POR_COSTO_LEGA_AÑO4" IS 'PORCENTAJE COSTO LEGALIZACION AÑO 1'
   COMMENT ON COLUMN "COND_GESTION"."VLR_CLOUD_AÑO2" IS 'VALOR CLOUD AÑO 2'
   COMMENT ON COLUMN "COND_GESTION"."VLR_CLOUD_AÑO3" IS 'VALOR CLOUD AÑO 2'
   COMMENT ON COLUMN "COND_GESTION"."VLR_CLOUD_AÑO4" IS 'VALOR CLOUD AÑO 3'
   COMMENT ON COLUMN "COND_GESTION"."POR_AJU_IMPUESTO_AÑO2" IS 'PORCENTAJE DE AJUSTE DE IMPUESTOS AÑO 2'
   COMMENT ON COLUMN "COND_GESTION"."POR_AJU_IMPUESTO_AÑO3" IS 'PORCENTAJE DE AJUSTE DE IMPUESTOS AÑO 3'
   COMMENT ON COLUMN "COND_GESTION"."POR_AJU_IMPUESTO_AÑO4" IS 'PORCENTAJE DE AJUSTE DE IMPUESTOS AÑO 4'
   COMMENT ON COLUMN "COND_GESTION"."SALDO_CONTRATOS_ANTERIORES" IS 'SALDO CONTRATOS ANTERIORES'
   COMMENT ON COLUMN "COND_GESTION"."VLR_CUO_SALDO_ANTERIOR" IS 'VALOR COMISION CONTRATOS ANTERORES'
   COMMENT ON TABLE "COND_GESTION"  IS 'CONDICIONES DE LA GESTION'
--------------------------------------------------------
--  DDL for Table CONTRATO
--------------------------------------------------------

  CREATE TABLE "CONTRATO" ("FACLIENTE_IDCLIENTE" NUMBER, "ID_CONTRATO" NUMBER(20,0), "ID_CONTRATO_CLIENTE" VARCHAR2(100 BYTE), "OBJETO" VARCHAR2(1000 BYTE), "MONEDA" VARCHAR2(3 BYTE), "FECHA_INICIO" DATE, "FECHA_FIN" DATE, "VALOR_CONTRATO" NUMBER(16,2), "RESPONSABLE_GESTION" VARCHAR2(100 BYTE), "OBSERVACIONES" VARCHAR2(2000 BYTE), "VALOR_AJUSTE" NUMBER DEFAULT 0) 

   COMMENT ON COLUMN "CONTRATO"."ID_CONTRATO" IS 'IDENTIFICACION INTERNA DEL CONTRATO'
   COMMENT ON COLUMN "CONTRATO"."ID_CONTRATO_CLIENTE" IS 'IDENTIFICACION DEL CONTRATO CON EL CLIENTE'
   COMMENT ON COLUMN "CONTRATO"."OBJETO" IS 'OBJETO DEL CONTRATO SEGUN EL DOCUMENTO FISICO'
   COMMENT ON COLUMN "CONTRATO"."MONEDA" IS 'MONEDA DE NEGOCIACION DEL CONTRATO'
   COMMENT ON COLUMN "CONTRATO"."FECHA_INICIO" IS 'FECHA INICIO DEL CONTRATO'
   COMMENT ON COLUMN "CONTRATO"."FECHA_FIN" IS 'FECHA FINALIZACION DEL CONTRATO'
   COMMENT ON COLUMN "CONTRATO"."VALOR_CONTRATO" IS 'VALOR BASE DEL CONTRATO'
   COMMENT ON COLUMN "CONTRATO"."RESPONSABLE_GESTION" IS 'RESPONSABLE INTERNO DE GESTIONAR EL CONTRATO'
   COMMENT ON COLUMN "CONTRATO"."OBSERVACIONES" IS 'HISTORIA DE OBSERVACIONES DEL CONTRATO'
   COMMENT ON COLUMN "CONTRATO"."VALOR_AJUSTE" IS 'ES EL VALOR POR EL CUAL EL TOTAL DE UN CONTRATO PUEDE SER MODIFICADO'
--------------------------------------------------------
--  DDL for Table CONTRATO_FORMA_PAGO
--------------------------------------------------------

  CREATE TABLE "CONTRATO_FORMA_PAGO" ("ID_CONTRATO_FORMA_PAGO" NUMBER DEFAULT NULL, "FORMA_PAGO" VARCHAR2(2000 BYTE), "VALOR_FORMA_PAGO" NUMBER, "ID_CONTRATO" NUMBER, "ID_FACTURA" NUMBER, "FECHA_PAGO_ESTIMADO" DATE) 

   COMMENT ON COLUMN "CONTRATO_FORMA_PAGO"."ID_CONTRATO_FORMA_PAGO" IS 'IDENTIFICADOR DEL REGISTRO DE LA FORMA PAGO'
   COMMENT ON COLUMN "CONTRATO_FORMA_PAGO"."FORMA_PAGO" IS 'DESCRIPCION DE LA FORMA PAGO'
   COMMENT ON COLUMN "CONTRATO_FORMA_PAGO"."VALOR_FORMA_PAGO" IS 'VALOR DE LA FORMA DE PAGO'
   COMMENT ON COLUMN "CONTRATO_FORMA_PAGO"."ID_CONTRATO" IS 'ID DEL CONTRATO AL QUE HACE REFERENCIA'
   COMMENT ON COLUMN "CONTRATO_FORMA_PAGO"."ID_FACTURA" IS 'ID DE LA FACTURA A LA QUE SE LE HA CRUZADO'
   COMMENT ON COLUMN "CONTRATO_FORMA_PAGO"."FECHA_PAGO_ESTIMADO" IS 'fecha estimada del pago de la forma de pago'
--------------------------------------------------------
--  DDL for Table FACLIENTE
--------------------------------------------------------

  CREATE TABLE "FACLIENTE" ("IDCLIENTE" NUMBER, "DOCUMENTO_TIPO" NUMBER, "DOCUMENTO_NUMERO" VARCHAR2(500 BYTE), "DOCUMENTO_DV" VARCHAR2(800 BYTE), "REGIMEN_FISCAL" NUMBER, "NOMBRE_COMERCIAL" VARCHAR2(800 BYTE), "OBLIGACIONES_FISCALES" NUMBER, "CONTACTO_TELEFONO" VARCHAR2(800 BYTE), "CONTACTO_CORREO" VARCHAR2(800 BYTE), "CONTACTO_NOTA" VARCHAR2(800 BYTE), "IMPUESTO" NUMBER, "UBICACION_PAIS" NUMBER, "UBICACION_DEPARTAMENTO" NUMBER, "UBICACION_CIUDAD" NUMBER, "UBICACION_DIRECCION" VARCHAR2(800 BYTE), "UBICACION_CODIGOPOSTAL" NUMBER(9,0), "TIPO_PERSONA" NUMBER) 

   COMMENT ON COLUMN "FACLIENTE"."IDCLIENTE" IS 'ID REGISTRO (CLIENTE)'
   COMMENT ON COLUMN "FACLIENTE"."DOCUMENTO_TIPO" IS 'TIPO DE DOCUMENTO'
   COMMENT ON COLUMN "FACLIENTE"."DOCUMENTO_DV" IS 'DV DEL DOCUMENTO'
   COMMENT ON COLUMN "FACLIENTE"."REGIMEN_FISCAL" IS 'ID DEL REGIMEN FISCAL'
   COMMENT ON COLUMN "FACLIENTE"."NOMBRE_COMERCIAL" IS 'NOMBRE COMERCIAL DEL CLIENTE
'
   COMMENT ON COLUMN "FACLIENTE"."OBLIGACIONES_FISCALES" IS 'ID DE LA OBLIGACION FISCAL'
   COMMENT ON COLUMN "FACLIENTE"."CONTACTO_TELEFONO" IS 'NUMERO DE TELEFONO DEL CLIENTE
'
   COMMENT ON COLUMN "FACLIENTE"."CONTACTO_CORREO" IS 'CORREO DEL CLIENTE'
   COMMENT ON COLUMN "FACLIENTE"."CONTACTO_NOTA" IS 'NOTA DEL CLIENTE'
   COMMENT ON COLUMN "FACLIENTE"."IMPUESTO" IS 'ID DEL IMPUESTO'
   COMMENT ON COLUMN "FACLIENTE"."UBICACION_PAIS" IS 'ID DEL PAIS'
   COMMENT ON COLUMN "FACLIENTE"."UBICACION_DEPARTAMENTO" IS 'ID DEL DEPARTAMENTO'
   COMMENT ON COLUMN "FACLIENTE"."UBICACION_CIUDAD" IS 'ID DE LA CIUDAD'
   COMMENT ON COLUMN "FACLIENTE"."UBICACION_DIRECCION" IS 'DIRECCION DEL CLIENTE'
   COMMENT ON COLUMN "FACLIENTE"."UBICACION_CODIGOPOSTAL" IS 'CODIGO POSTAL DEL CLIENTE'
   COMMENT ON COLUMN "FACLIENTE"."TIPO_PERSONA" IS 'TIPO DE PERSONA DEL CLIENTE'
--------------------------------------------------------
--  DDL for Table FACTCONT
--------------------------------------------------------

  CREATE TABLE "FACTCONT" ("CONTRATO_ID_CONTRATO" NUMBER(20,0), "FAFACTURA_IDFACTURA" NUMBER, "AÑO_CONTRATO" NUMBER(4,0)) 

   COMMENT ON TABLE "FACTCONT"  IS 'FACTURAS GENERADAS DEL CONTRATO'
--------------------------------------------------------
--  DDL for Table FACTURA_ARCHIVOS
--------------------------------------------------------

  CREATE TABLE "FACTURA_ARCHIVOS" ("ID_FACT_ARCHIVO" NUMBER DEFAULT NULL, "NOMBRE_ARCHIVO" VARCHAR2(200 BYTE), "EXTENSION_ARCHIVO" VARCHAR2(20 BYTE), "BASE_ARCHIVO" CLOB, "ID_FACTURA" NUMBER, "ID_CONTRATO" NUMBER) 

   COMMENT ON COLUMN "FACTURA_ARCHIVOS"."ID_FACT_ARCHIVO" IS 'ID DEL REGISTRO'
   COMMENT ON COLUMN "FACTURA_ARCHIVOS"."NOMBRE_ARCHIVO" IS 'NOMBRE DEL ARCHIVO'
   COMMENT ON COLUMN "FACTURA_ARCHIVOS"."EXTENSION_ARCHIVO" IS 'EXTENSION DEL ARCHIVO'
   COMMENT ON COLUMN "FACTURA_ARCHIVOS"."BASE_ARCHIVO" IS 'BASE 64 DEL ARCHIVO'
   COMMENT ON COLUMN "FACTURA_ARCHIVOS"."ID_FACTURA" IS 'ID DE LA FACTURA A LA QUE EL ARCHIVO HACE REFERENCIA'
   COMMENT ON COLUMN "FACTURA_ARCHIVOS"."ID_CONTRATO" IS 'ID DEL CONTRATO AL CUAL EL ARCHIVO HACE REFERENCIA'
--------------------------------------------------------
--  DDL for Table FAFACTURA
--------------------------------------------------------

  CREATE TABLE "FAFACTURA" ("IDFACTURA" NUMBER, "TIPO_DOCUMENTO" NUMBER, "FACTURA_NUMERACION_ACTUAL" VARCHAR2(500 BYTE), "FACTURA_PREFIJO" VARCHAR2(20 BYTE), "FECHA_EXPEDICION" DATE, "FECHA_VENCIMIENTO" DATE, "ORDEN_COMPRA_ID" VARCHAR2(500 BYTE), "ORDEN_COMPRA_FECHA" DATE, "FORMA_PAGO" NUMBER, "MEDIO_PAGO" NUMBER, "MONEDA" NUMBER, "VALOR_LETRAS" VARCHAR2(500 BYTE), "TASA_CAMBIO" NUMBER, "DOCUMENTO_REFERENCIA_PREFIJO" VARCHAR2(20 BYTE), "DOCUMENTO_REFERENCIA_NUMERO_FACTURA" NVARCHAR2(500), "DOCUMENTO_REFERENCIA_FECHA_EXPEDICION" DATE, "DOCUMENTO_REFERENCIA_UUID" VARCHAR2(500 BYTE), "IDCLIENTE" NUMBER, "UUID" VARCHAR2(500 BYTE), "NOTA" NUMBER, "IDCONTRATO" NUMBER, "CREATED_MANUALLY" NUMBER DEFAULT 0) 

   COMMENT ON COLUMN "FAFACTURA"."IDFACTURA" IS 'ID DEL REGISTRO'
   COMMENT ON COLUMN "FAFACTURA"."TIPO_DOCUMENTO" IS 'TIPO DE DOCUMENTO DE FACTURA'
   COMMENT ON COLUMN "FAFACTURA"."FACTURA_NUMERACION_ACTUAL" IS 'NUMERACION ACTUAL DE FACTURA'
   COMMENT ON COLUMN "FAFACTURA"."FACTURA_PREFIJO" IS 'PREFIJO FACTURA'
   COMMENT ON COLUMN "FAFACTURA"."FECHA_EXPEDICION" IS 'FECHA DE EXPEDICION FACTURA'
   COMMENT ON COLUMN "FAFACTURA"."FECHA_VENCIMIENTO" IS 'FECHA DE VENCIMIENTO FACTURA'
   COMMENT ON COLUMN "FAFACTURA"."ORDEN_COMPRA_ID" IS 'ID DE LA ORDEN DE COMPRA'
   COMMENT ON COLUMN "FAFACTURA"."ORDEN_COMPRA_FECHA" IS 'FECHA DE LA ORDEN DE COMPRA'
   COMMENT ON COLUMN "FAFACTURA"."FORMA_PAGO" IS 'ID DE LA FORMA DE PAGO'
   COMMENT ON COLUMN "FAFACTURA"."MEDIO_PAGO" IS 'ID DEL MEDIO PAGO'
   COMMENT ON COLUMN "FAFACTURA"."MONEDA" IS 'ID DE LA MONEDA DE PAGO'
   COMMENT ON COLUMN "FAFACTURA"."VALOR_LETRAS" IS 'VALOR EN LETRAS
'
   COMMENT ON COLUMN "FAFACTURA"."TASA_CAMBIO" IS 'VALOR DE LA TASA DE CAMBIO'
   COMMENT ON COLUMN "FAFACTURA"."DOCUMENTO_REFERENCIA_PREFIJO" IS 'PREFIJO DEL DOCUMENTO DE REFERENCIA'
   COMMENT ON COLUMN "FAFACTURA"."DOCUMENTO_REFERENCIA_NUMERO_FACTURA" IS 'NUMERO FACTURA DEL DOCUMENTO DE REFERENCIA'
   COMMENT ON COLUMN "FAFACTURA"."DOCUMENTO_REFERENCIA_FECHA_EXPEDICION" IS 'FECHA DE EXPEDICION DEL DOCUMENTO DE REFERENCIA'
   COMMENT ON COLUMN "FAFACTURA"."DOCUMENTO_REFERENCIA_UUID" IS 'UUID DEL DOCUMENTO DE REFERENCIA'
   COMMENT ON COLUMN "FAFACTURA"."IDCLIENTE" IS 'ID DEL CLIENTE'
   COMMENT ON COLUMN "FAFACTURA"."UUID" IS 'CUFE O CUDE DE LA FACTURA'
   COMMENT ON COLUMN "FAFACTURA"."NOTA" IS 'ID DE LA NOTA CREADA'
   COMMENT ON COLUMN "FAFACTURA"."IDCONTRATO" IS 'ID DEL CONTRATO RELACIONADO A ESTA FACTURA'
   COMMENT ON COLUMN "FAFACTURA"."CREATED_MANUALLY" IS 'VALOR BOOLEANO PARA SABER SI ESTÁ FACTURA FUE CREADA MANUAL O AUTOMATICAMENTE DESDE EL SISTEMA DE FACTURACION ELECTRONICA, 0 ES QUE NO FUE MANUAL, 1 ES QUE SI'
--------------------------------------------------------
--  DDL for Table FAHISTORICO_FACTURADO
--------------------------------------------------------

  CREATE TABLE "FAHISTORICO_FACTURADO" ("ID" NUMBER DEFAULT NULL, "IDFACTURA" NUMBER, "FACT_ENE" NUMBER, "FACT_FEB" NUMBER, "FACT_MAR" NUMBER, "FACT_ABR" NUMBER, "FACT_MAY" NUMBER, "FACT_JUN" NUMBER, "FACT_JUL" NUMBER, "FACT_AGO" NUMBER, "FACT_SEP" NUMBER, "FACT_OCT" NUMBER, "FACT_NOV" NUMBER, "FACT_DIC" NUMBER, "NOMBRE_COMERCIAL" VARCHAR2(1000 BYTE), "DESC_MONEDA" VARCHAR2(80 BYTE), "FECHA_EXP" DATE, "FECHA_VENC" DATE, "VALOR_TOTAL" NUMBER, "TOTAL_IMPUESTOS" NUMBER, "TOTAL_FACTURAS" NUMBER, "ANIO_FACTURADO" NUMBER DEFAULT TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))) 

   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."ID" IS 'ID DEL REGISTRO AUTOINCREMENTABLE CON SECUENCIA'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."IDFACTURA" IS 'ID DE LA FACTURA'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_ENE" IS 'FACTURADO EN ENERO'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_FEB" IS 'FACTURADO EN FEBRERO'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_MAR" IS 'FACTURADO EN MARZO'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_ABR" IS 'FACTURADO EN ABRIL'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_MAY" IS 'FACTURADO EN MAYO
'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_JUN" IS 'FACTURADO EN JUNIO'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_JUL" IS 'FACTURADO EN JULIO'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_AGO" IS 'FACTURADO EN AGOSTO'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_SEP" IS 'FACTURADO EN SEPTIEMBRE'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_OCT" IS 'FACTURADO EN OCTUBRE
'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_NOV" IS 'FACTURADO EN NOVIEMBRE'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FACT_DIC" IS 'FACTURADO EN DICIEMBRE'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."NOMBRE_COMERCIAL" IS 'NOMBRE DE LA EMPRESA'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."DESC_MONEDA" IS 'DESCRIPCION DE LA MONEDA'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FECHA_EXP" IS 'FECHA DE EXPEDICION DE FACTURA'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."FECHA_VENC" IS 'FECHA DE VENCIMIENTO FACTURA'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."VALOR_TOTAL" IS 'VALOR TOTAL FACTURADO'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."TOTAL_IMPUESTOS" IS 'VALOR TOTAL DE IMPUESTOS'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."TOTAL_FACTURAS" IS 'CANTIDAD DE PRODUCTOS LIGADOS A LA FACTURA'
   COMMENT ON COLUMN "FAHISTORICO_FACTURADO"."ANIO_FACTURADO" IS 'AÑO EN QUE FUE FACTURADO'
--------------------------------------------------------
--  DDL for Table FAPRODUCTO
--------------------------------------------------------

  CREATE TABLE "FAPRODUCTO" ("IDPRODUCTO" NUMBER, "CANTIDAD_BASE" VARCHAR2(500 BYTE), "CANTIDAD_SOLICITADA" VARCHAR2(500 BYTE), "DESCIPCION" VARCHAR2(4000 BYTE), "ID" VARCHAR2(100 BYTE), "IMPUESTO_ID" NUMBER, "ITEM_ID" NUMBER, "PORCENTAJE_IMPUESTO" VARCHAR2(200 BYTE), "PRECIO_BASE" NUMBER, "PRECIO_BRUTO" NUMBER, "PRECIO_NETO" NUMBER, "STANDAR_ITEM" NUMBER, "UNIDAD_MEDIDA" NUMBER, "VALOR_IMPUESTO" NUMBER, "AGG" VARCHAR2(10 BYTE), "IDFACTURA" NUMBER) 

   COMMENT ON COLUMN "FAPRODUCTO"."IDPRODUCTO" IS 'ID DEL REGISTRO
'
   COMMENT ON COLUMN "FAPRODUCTO"."CANTIDAD_BASE" IS 'CANTIDAD BASE DEL PRODUCTO'
   COMMENT ON COLUMN "FAPRODUCTO"."CANTIDAD_SOLICITADA" IS 'CANTIDAD SOLICITADA DEL PRODUCTO'
   COMMENT ON COLUMN "FAPRODUCTO"."DESCIPCION" IS 'DESCRIPCION DEL PRODUCTO'
   COMMENT ON COLUMN "FAPRODUCTO"."ID" IS 'ID DE PRODUCTO'
   COMMENT ON COLUMN "FAPRODUCTO"."IMPUESTO_ID" IS 'ID DEL IMPUESTO'
   COMMENT ON COLUMN "FAPRODUCTO"."ITEM_ID" IS 'ID DEL ITEM'
   COMMENT ON COLUMN "FAPRODUCTO"."PORCENTAJE_IMPUESTO" IS 'PORCENTAJE DEL IMPUESTO
'
   COMMENT ON COLUMN "FAPRODUCTO"."PRECIO_BASE" IS 'PRECIO BASE DEL PRODUCTO'
   COMMENT ON COLUMN "FAPRODUCTO"."PRECIO_BRUTO" IS 'PRECIO BRUTO DEL PRODUCTO'
   COMMENT ON COLUMN "FAPRODUCTO"."PRECIO_NETO" IS 'PRECIO NETO DEL PRODUCTO'
   COMMENT ON COLUMN "FAPRODUCTO"."STANDAR_ITEM" IS 'ID DEL STANDAR ITEM'
   COMMENT ON COLUMN "FAPRODUCTO"."UNIDAD_MEDIDA" IS 'ID DE LA UNIDAD DE MEDIDA'
   COMMENT ON COLUMN "FAPRODUCTO"."VALOR_IMPUESTO" IS 'VALOR DEL IMPUESTO'
   COMMENT ON COLUMN "FAPRODUCTO"."AGG" IS 'VALOR BOOLEANO'
   COMMENT ON COLUMN "FAPRODUCTO"."IDFACTURA" IS 'ID DE LA FACTURA (LLAVE FORANEA)'
--------------------------------------------------------
--  DDL for Table FERESPONFISCALES
--------------------------------------------------------

  CREATE TABLE "FERESPONFISCALES" ("ID" NUMBER, "DESCRIPCION" VARCHAR2(200 BYTE)) 

   COMMENT ON COLUMN "FERESPONFISCALES"."ID" IS 'ID DE LA RESPONSABILIDAD FISCAL'
   COMMENT ON COLUMN "FERESPONFISCALES"."DESCRIPCION" IS 'DESCRIPCION DE LA RESPONSABILIDAD FISCAL'
--------------------------------------------------------
--  DDL for Table INT_MESAENVWS
--------------------------------------------------------

  CREATE TABLE "INT_MESAENVWS" ("IDCOMPANY" NUMBER(10,0) INVISIBLE DEFAULT SYS_CONTEXT('lbac$0_lab', 'lbac$default_row_tag'), "MESACODI" NUMBER(10,0), "MESAFECH" DATE, "MESAXMLENV" CLOB, "MESAESTADO" NUMBER(1,0), "MESAINTENTOS" NUMBER(5,0), "MESAWEBSERVICE" VARCHAR2(1000 BYTE), "MESAHTTPERROR" VARCHAR2(2000 BYTE), "MESATRACEERROR" VARCHAR2(2000 BYTE), "MESASOAPERROR" CLOB, "MESAISSOAPERROR" NUMBER(2,0), "MESAISHTTPERROR" NUMBER(2,0), "MESAXMLPAYLOAD" CLOB, "MESAFECHAINI" DATE, "MESAFECHAFIN" DATE, "MESAEXTID" NUMBER(10,0), "MESADEFI" VARCHAR2(200 BYTE))
--------------------------------------------------------
--  DDL for Table LV_FAILED_JOBS
--------------------------------------------------------

  CREATE TABLE "LV_FAILED_JOBS" ("ID" NUMBER(19,0), "CONNECTION" CLOB, "QUEUE" CLOB, "PAYLOAD" CLOB, "EXCEPTION" CLOB, "FAILED_AT" TIMESTAMP (6))
--------------------------------------------------------
--  DDL for Table LV_PASSWORD_RESETS
--------------------------------------------------------

  CREATE TABLE "LV_PASSWORD_RESETS" ("EMAIL" VARCHAR2(255 BYTE), "TOKEN" VARCHAR2(255 BYTE), "CREATED_AT" TIMESTAMP (6))
--------------------------------------------------------
--  DDL for Table LV_USERS
--------------------------------------------------------

  CREATE TABLE "LV_USERS" ("ID" NUMBER(19,0), "NAME" VARCHAR2(255 BYTE), "EMAIL" VARCHAR2(255 BYTE), "EMAIL_VERIFIED_AT" TIMESTAMP (6), "PASSWORD" VARCHAR2(255 BYTE), "REMEMBER_TOKEN" VARCHAR2(100 BYTE), "CREATED_AT" TIMESTAMP (6), "UPDATED_AT" TIMESTAMP (6), "IS_ADMIN" VARCHAR2(255 BYTE) DEFAULT 'N')
--------------------------------------------------------
--  DDL for Table MIGRATIONS
--------------------------------------------------------

  CREATE TABLE "MIGRATIONS" ("ID" NUMBER(10,0), "MIGRATION" VARCHAR2(255 BYTE), "BATCH" NUMBER(10,0))
--------------------------------------------------------
--  DDL for Table MODI_CONTRATO
--------------------------------------------------------

  CREATE TABLE "MODI_CONTRATO" ("TIPO_MODIFICACION" VARCHAR2(20 BYTE), "MODIFICA_TIEMPO" VARCHAR2(1 BYTE), "MODIFICA_VALOR" VARCHAR2(1 BYTE), "FECHA_MODIFICACION" DATE, "VALOR_MODIFICACION" NUMBER(13,2), "CONTRATO_ID_CONTRATO" NUMBER(20,0)) 

   COMMENT ON COLUMN "MODI_CONTRATO"."TIPO_MODIFICACION" IS 'TIPO DE MODIFICACION AL CONTRATO (ADICION, SUSPENSION, REINICIO)'
   COMMENT ON COLUMN "MODI_CONTRATO"."MODIFICA_TIEMPO" IS 'MODIFICA EL TIEMPO DEL CONTRATO'
   COMMENT ON COLUMN "MODI_CONTRATO"."MODIFICA_VALOR" IS 'MODIFICA VALOR DEL CONTRATO'
   COMMENT ON COLUMN "MODI_CONTRATO"."FECHA_MODIFICACION" IS 'FECHA EN QUE SE HIZO LA MODIFICACION'
   COMMENT ON COLUMN "MODI_CONTRATO"."VALOR_MODIFICACION" IS 'VALOR EN DINERO DE LA MODIFICACION'
   COMMENT ON TABLE "MODI_CONTRATO"  IS 'MODIFICACIONES AL CONTRATO'
--------------------------------------------------------
--  DDL for Table SYNC_FACTRO
--------------------------------------------------------

  CREATE TABLE "SYNC_FACTRO" ("ID_SYNC_FACTRO" NUMBER, "FECHA_REGISTRO" DATE DEFAULT SYSDATE, "PAYLOAD" CLOB, "PROCESADO" VARCHAR2(20 BYTE) DEFAULT 'NO', "FECHA_PROCESADO" DATE) 

   COMMENT ON COLUMN "SYNC_FACTRO"."ID_SYNC_FACTRO" IS 'PK'
   COMMENT ON COLUMN "SYNC_FACTRO"."FECHA_REGISTRO" IS 'FECHA DE REGISTRO'
   COMMENT ON COLUMN "SYNC_FACTRO"."PAYLOAD" IS 'JSON CON LA INFO A SINCRONIZAR'
   COMMENT ON COLUMN "SYNC_FACTRO"."PROCESADO" IS 'ESTADO DE PROCESO DEL PAYLOAD'
   COMMENT ON COLUMN "SYNC_FACTRO"."FECHA_PROCESADO" IS 'FECHA DE PROCESADO'
--------------------------------------------------------
--  DDL for Table TRAZA_PROCESS
--------------------------------------------------------

  CREATE TABLE "TRAZA_PROCESS" ("ID_TRAZA" NUMBER, "FECHA_REGISTRO" DATE DEFAULT sysdate, "PKG_PRC_NAME" VARCHAR2(200 BYTE), "ERR_MSG" VARCHAR2(4000 BYTE), "PROCESS_PAYLOAD" CLOB) 

   COMMENT ON COLUMN "TRAZA_PROCESS"."ID_TRAZA" IS 'pk de la tabla'
   COMMENT ON COLUMN "TRAZA_PROCESS"."FECHA_REGISTRO" IS 'fecha en la que se registra'
   COMMENT ON COLUMN "TRAZA_PROCESS"."PKG_PRC_NAME" IS 'nombre del paquete o prc'
   COMMENT ON COLUMN "TRAZA_PROCESS"."ERR_MSG" IS 'mensaje de error de la excepcion'
   COMMENT ON COLUMN "TRAZA_PROCESS"."PROCESS_PAYLOAD" IS 'payload del proceso'
--------------------------------------------------------
--  Constraints for Table AGENTE
--------------------------------------------------------

  ALTER TABLE "AGENTE" MODIFY ("COD_AGENTE" NOT NULL ENABLE)
  ALTER TABLE "AGENTE" ADD CONSTRAINT "AGENTE_PK" PRIMARY KEY ("COD_AGENTE") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table CALC_GESTION
--------------------------------------------------------

  ALTER TABLE "CALC_GESTION" MODIFY ("AGENTE_COD_AGENTE" NOT NULL ENABLE)
  ALTER TABLE "CALC_GESTION" MODIFY ("FACTCONT_CONTRATO_ID_CONTRATO" NOT NULL ENABLE)
  ALTER TABLE "CALC_GESTION" MODIFY ("FACTCONT_FAFACTURA_IDFACTURA" NOT NULL ENABLE)
  ALTER TABLE "CALC_GESTION" ADD CONSTRAINT "CALC_GESTION_PK" PRIMARY KEY ("AGENTE_COD_AGENTE", "FACTCONT_CONTRATO_ID_CONTRATO", "FACTCONT_FAFACTURA_IDFACTURA") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table COND_GESTION
--------------------------------------------------------

  ALTER TABLE "COND_GESTION" MODIFY ("AGENTE_COD_AGENTE" NOT NULL ENABLE)
  ALTER TABLE "COND_GESTION" MODIFY ("CONTRATO_ID_CONTRATO" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "CONTRATO" MODIFY ("FACLIENTE_IDCLIENTE" NOT NULL ENABLE)
  ALTER TABLE "CONTRATO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE)
  ALTER TABLE "CONTRATO" ADD CONSTRAINT "CONTRATO_PK" PRIMARY KEY ("ID_CONTRATO") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table CONTRATO_FORMA_PAGO
--------------------------------------------------------

  ALTER TABLE "CONTRATO_FORMA_PAGO" MODIFY ("ID_CONTRATO_FORMA_PAGO" NOT NULL ENABLE)
  ALTER TABLE "CONTRATO_FORMA_PAGO" MODIFY ("FORMA_PAGO" NOT NULL ENABLE)
  ALTER TABLE "CONTRATO_FORMA_PAGO" MODIFY ("VALOR_FORMA_PAGO" NOT NULL ENABLE)
  ALTER TABLE "CONTRATO_FORMA_PAGO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE)
  ALTER TABLE "CONTRATO_FORMA_PAGO" ADD CONSTRAINT "CONTRATO_FORMA_PAGO_PK" PRIMARY KEY ("ID_CONTRATO_FORMA_PAGO") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table FACLIENTE
--------------------------------------------------------

  ALTER TABLE "FACLIENTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE)
  ALTER TABLE "FACLIENTE" MODIFY ("DOCUMENTO_TIPO" NOT NULL ENABLE)
  ALTER TABLE "FACLIENTE" MODIFY ("DOCUMENTO_NUMERO" NOT NULL ENABLE)
  ALTER TABLE "FACLIENTE" ADD CONSTRAINT "FECLIENTE_PK" PRIMARY KEY ("IDCLIENTE") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table FACTCONT
--------------------------------------------------------

  ALTER TABLE "FACTCONT" MODIFY ("CONTRATO_ID_CONTRATO" NOT NULL ENABLE)
  ALTER TABLE "FACTCONT" MODIFY ("FAFACTURA_IDFACTURA" NOT NULL ENABLE)
  ALTER TABLE "FACTCONT" ADD CONSTRAINT "FACTCONT_PK" PRIMARY KEY ("CONTRATO_ID_CONTRATO", "FAFACTURA_IDFACTURA") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table FACTURA_ARCHIVOS
--------------------------------------------------------

  ALTER TABLE "FACTURA_ARCHIVOS" MODIFY ("ID_FACT_ARCHIVO" NOT NULL ENABLE)
  ALTER TABLE "FACTURA_ARCHIVOS" MODIFY ("NOMBRE_ARCHIVO" NOT NULL ENABLE)
  ALTER TABLE "FACTURA_ARCHIVOS" MODIFY ("BASE_ARCHIVO" NOT NULL ENABLE)
  ALTER TABLE "FACTURA_ARCHIVOS" ADD CONSTRAINT "FACTURA_ARCHIVOS_PK" PRIMARY KEY ("ID_FACT_ARCHIVO") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table FAFACTURA
--------------------------------------------------------

  ALTER TABLE "FAFACTURA" MODIFY ("IDFACTURA" NOT NULL ENABLE)
  ALTER TABLE "FAFACTURA" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE)
  ALTER TABLE "FAFACTURA" MODIFY ("FACTURA_NUMERACION_ACTUAL" NOT NULL ENABLE)
  ALTER TABLE "FAFACTURA" ADD CONSTRAINT "FEFACTURA_PK" PRIMARY KEY ("IDFACTURA") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table FAHISTORICO_FACTURADO
--------------------------------------------------------

  ALTER TABLE "FAHISTORICO_FACTURADO" MODIFY ("ID" NOT NULL ENABLE)
  ALTER TABLE "FAHISTORICO_FACTURADO" ADD CONSTRAINT "FAHISTORICO_FACTURADO_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table FAPRODUCTO
--------------------------------------------------------

  ALTER TABLE "FAPRODUCTO" MODIFY ("IDPRODUCTO" NOT NULL ENABLE)
  ALTER TABLE "FAPRODUCTO" MODIFY ("IDFACTURA" NOT NULL ENABLE)
  ALTER TABLE "FAPRODUCTO" ADD CONSTRAINT "FEPRODUCTOS_PK" PRIMARY KEY ("IDPRODUCTO") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table FERESPONFISCALES
--------------------------------------------------------

  ALTER TABLE "FERESPONFISCALES" MODIFY ("ID" NOT NULL ENABLE)
  ALTER TABLE "FERESPONFISCALES" MODIFY ("DESCRIPCION" NOT NULL ENABLE)
  ALTER TABLE "FERESPONFISCALES" ADD CONSTRAINT "FERESPONFISCALES_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table INT_MESAENVWS
--------------------------------------------------------

  ALTER TABLE "INT_MESAENVWS" MODIFY ("MESACODI" NOT NULL ENABLE)
  ALTER TABLE "INT_MESAENVWS" MODIFY ("MESADEFI" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table LV_FAILED_JOBS
--------------------------------------------------------

  ALTER TABLE "LV_FAILED_JOBS" MODIFY ("ID" NOT NULL ENABLE)
  ALTER TABLE "LV_FAILED_JOBS" MODIFY ("CONNECTION" NOT NULL ENABLE)
  ALTER TABLE "LV_FAILED_JOBS" MODIFY ("QUEUE" NOT NULL ENABLE)
  ALTER TABLE "LV_FAILED_JOBS" MODIFY ("PAYLOAD" NOT NULL ENABLE)
  ALTER TABLE "LV_FAILED_JOBS" MODIFY ("EXCEPTION" NOT NULL ENABLE)
  ALTER TABLE "LV_FAILED_JOBS" MODIFY ("FAILED_AT" NOT NULL ENABLE)
  ALTER TABLE "LV_FAILED_JOBS" ADD CONSTRAINT "LV_FAILED_JOBS_ID_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table LV_PASSWORD_RESETS
--------------------------------------------------------

  ALTER TABLE "LV_PASSWORD_RESETS" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "LV_PASSWORD_RESETS" MODIFY ("TOKEN" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table LV_USERS
--------------------------------------------------------

  ALTER TABLE "LV_USERS" MODIFY ("ID" NOT NULL ENABLE)
  ALTER TABLE "LV_USERS" MODIFY ("NAME" NOT NULL ENABLE)
  ALTER TABLE "LV_USERS" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "LV_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE)
  ALTER TABLE "LV_USERS" ADD CONSTRAINT "LV_USERS_ID_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
  ALTER TABLE "LV_USERS" MODIFY ("IS_ADMIN" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table MIGRATIONS
--------------------------------------------------------

  ALTER TABLE "MIGRATIONS" MODIFY ("ID" NOT NULL ENABLE)
  ALTER TABLE "MIGRATIONS" MODIFY ("MIGRATION" NOT NULL ENABLE)
  ALTER TABLE "MIGRATIONS" MODIFY ("BATCH" NOT NULL ENABLE)
  ALTER TABLE "MIGRATIONS" ADD CONSTRAINT "MIGRATIONS_ID_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table MODI_CONTRATO
--------------------------------------------------------

  ALTER TABLE "MODI_CONTRATO" MODIFY ("CONTRATO_ID_CONTRATO" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table SYNC_FACTRO
--------------------------------------------------------

  ALTER TABLE "SYNC_FACTRO" MODIFY ("ID_SYNC_FACTRO" NOT NULL ENABLE)
  ALTER TABLE "SYNC_FACTRO" MODIFY ("PAYLOAD" NOT NULL ENABLE)
  ALTER TABLE "SYNC_FACTRO" ADD CONSTRAINT "SYNC_FACTRO_PK" PRIMARY KEY ("ID_SYNC_FACTRO") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table TRAZA_PROCESS
--------------------------------------------------------

  ALTER TABLE "TRAZA_PROCESS" MODIFY ("ID_TRAZA" NOT NULL ENABLE)
  ALTER TABLE "TRAZA_PROCESS" MODIFY ("PKG_PRC_NAME" NOT NULL ENABLE)
  ALTER TABLE "TRAZA_PROCESS" ADD CONSTRAINT "TRAZA_PROCESS_PK" PRIMARY KEY ("ID_TRAZA") USING INDEX  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ABONO_AGENTE
--------------------------------------------------------

  ALTER TABLE "ABONO_AGENTE" ADD CONSTRAINT "AGENTE_FK" FOREIGN KEY ("AGENTE_COD_AGENTE") REFERENCES "AGENTE" ("COD_AGENTE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CALC_GESTION
--------------------------------------------------------

  ALTER TABLE "CALC_GESTION" ADD CONSTRAINT "CALC_GESTION_AGENTE_FK" FOREIGN KEY ("AGENTE_COD_AGENTE") REFERENCES "AGENTE" ("COD_AGENTE") ENABLE
  ALTER TABLE "CALC_GESTION" ADD CONSTRAINT "CALC_GESTION_FK1" FOREIGN KEY ("FACTCONT_FAFACTURA_IDFACTURA") REFERENCES "FAFACTURA" ("IDFACTURA") ENABLE
  ALTER TABLE "CALC_GESTION" ADD CONSTRAINT "CALC_GESTION_FK2" FOREIGN KEY ("FACTCONT_CONTRATO_ID_CONTRATO") REFERENCES "CONTRATO" ("ID_CONTRATO") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table COND_GESTION
--------------------------------------------------------

  ALTER TABLE "COND_GESTION" ADD CONSTRAINT "COND_GESTION_AGENTE_FK" FOREIGN KEY ("AGENTE_COD_AGENTE") REFERENCES "AGENTE" ("COD_AGENTE") ENABLE
  ALTER TABLE "COND_GESTION" ADD CONSTRAINT "COND_GESTION_CONTRATO_FK" FOREIGN KEY ("CONTRATO_ID_CONTRATO") REFERENCES "CONTRATO" ("ID_CONTRATO") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "CONTRATO" ADD CONSTRAINT "CONTRATO_FACLIENTE_FK" FOREIGN KEY ("FACLIENTE_IDCLIENTE") REFERENCES "FACLIENTE" ("IDCLIENTE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CONTRATO_FORMA_PAGO
--------------------------------------------------------

  ALTER TABLE "CONTRATO_FORMA_PAGO" ADD CONSTRAINT "FK_CONTRATO_FORMA_PAGO_CONTRATO" FOREIGN KEY ("ID_CONTRATO") REFERENCES "CONTRATO" ("ID_CONTRATO") ENABLE
  ALTER TABLE "CONTRATO_FORMA_PAGO" ADD CONSTRAINT "FK_ID_FACTURA_FAFACTURA" FOREIGN KEY ("ID_FACTURA") REFERENCES "FAFACTURA" ("IDFACTURA") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table FACTCONT
--------------------------------------------------------

  ALTER TABLE "FACTCONT" ADD CONSTRAINT "FACTCONT_CONTRATO_FK" FOREIGN KEY ("CONTRATO_ID_CONTRATO") REFERENCES "CONTRATO" ("ID_CONTRATO") ENABLE
  ALTER TABLE "FACTCONT" ADD CONSTRAINT "FACTCONT_FAFACTURA_FK" FOREIGN KEY ("FAFACTURA_IDFACTURA") REFERENCES "FAFACTURA" ("IDFACTURA") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table FACTURA_ARCHIVOS
--------------------------------------------------------

  ALTER TABLE "FACTURA_ARCHIVOS" ADD CONSTRAINT "FK_ID_CONTRATO_CONTRATO" FOREIGN KEY ("ID_CONTRATO") REFERENCES "CONTRATO" ("ID_CONTRATO") ENABLE
  ALTER TABLE "FACTURA_ARCHIVOS" ADD CONSTRAINT "FK_FAFACTURA_FACTURA_ARCHIVOS" FOREIGN KEY ("ID_FACTURA") REFERENCES "FAFACTURA" ("IDFACTURA") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table FAFACTURA
--------------------------------------------------------

  ALTER TABLE "FAFACTURA" ADD CONSTRAINT "IDCLIENTE_FEFACTURA_FECLIENTE" FOREIGN KEY ("IDCLIENTE") REFERENCES "FACLIENTE" ("IDCLIENTE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table FAPRODUCTO
--------------------------------------------------------

  ALTER TABLE "FAPRODUCTO" ADD CONSTRAINT "IDFACTURA_FEFACTURA_FEPRODUCTO" FOREIGN KEY ("IDFACTURA") REFERENCES "FAFACTURA" ("IDFACTURA") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table MODI_CONTRATO
--------------------------------------------------------

  ALTER TABLE "MODI_CONTRATO" ADD CONSTRAINT "MODI_CONTRATO_CONTRATO_FK" FOREIGN KEY ("CONTRATO_ID_CONTRATO") REFERENCES "CONTRATO" ("ID_CONTRATO") ENABLE
